services:
  user-app:
    environment:
      - APP_PORT=${APP_PORT}
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2

  user-db:
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE} 