# Server configuration
server.port=${APP_PORT:8081}

# PostgreSQL configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sparkflow_user}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB configuration (optional)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/sparkflow_user}
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

# OpenAPI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html 